services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run start

  backend:
    volumes:
      - ./backend:/app
      - ~/.gradle:/root/.gradle
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
